// Where uploaded documents live. Two backends, chosen by config:
//   STORAGE_BACKEND=local       files on disk in DATA_DIR/files (the default, what the QNAP uses)
//   STORAGE_BACKEND=azure-blob  a private Azure Blob Storage container, reached with a managed identity
// Both expose the same three calls: putFile, openRead and remove.
import fs from 'node:fs';
import path from 'node:path';

// Stored names are generated by this app (a UUID plus a checked extension), but every backend
// still refuses anything that could climb out of its folder.
const SAFE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const SAFE_PREFIX = /^([a-z0-9][a-z0-9-]{0,62}\/)?$/;

function safeName(name) {
  if (!SAFE_NAME.test(name) || name.includes('..')) throw new Error(`Unsafe file name: ${name}`);
  return name;
}

export function createLocalStorage(dir) {
  fs.mkdirSync(dir, { recursive: true });
  const fileFor = (name) => path.join(dir, safeName(name));

  return {
    backend: 'local',

    /** Moves a finished upload into place. */
    async putFile(name, sourcePath) {
      const target = fileFor(name);
      try {
        await fs.promises.rename(sourcePath, target);
      } catch (err) {
        if (err.code !== 'EXDEV') throw err; // the temp folder was on another disk: copy instead
        await fs.promises.copyFile(sourcePath, target);
        await fs.promises.rm(sourcePath, { force: true });
      }
    },

    /** Returns { stream, size }, or null when the file is missing. */
    async openRead(name) {
      const file = fileFor(name);
      try {
        const { size } = await fs.promises.stat(file);
        return { stream: fs.createReadStream(file), size };
      } catch (err) {
        if (err.code === 'ENOENT') return null;
        throw err;
      }
    },

    async remove(name) {
      await fs.promises.rm(fileFor(name), { force: true });
    },
  };
}

/**
 * A Blob service client. In Azure it signs in with the app's managed identity (no keys).
 * `connectionString` exists only for the local Azurite emulator, never for a real account.
 */
export async function createBlobService({ account, connectionString }) {
  if (!connectionString && !account) throw new Error('Set AZURE_STORAGE_ACCOUNT (or AZURE_STORAGE_CONNECTION_STRING for the emulator)');
  const { BlobServiceClient } = await import('@azure/storage-blob');
  if (connectionString) return BlobServiceClient.fromConnectionString(connectionString);
  const { DefaultAzureCredential } = await import('@azure/identity');
  return new BlobServiceClient(`https://${account}.blob.core.windows.net`, new DefaultAzureCredential());
}

/**
 * Azure Blob Storage backend.
 * `prefix` puts every blob under a folder, which is how each household gets its own area.
 */
export async function createBlobStorage({ account, container, connectionString, prefix = '', createContainer = false }) {
  if (!container) throw new Error('AZURE_STORAGE_CONTAINER is required');
  if (!SAFE_PREFIX.test(prefix)) throw new Error(`Unsafe blob prefix: ${prefix}`);

  const service = await createBlobService({ account, connectionString });
  const containerClient = service.getContainerClient(container);
  if (createContainer) await containerClient.createIfNotExists();
  const blobFor = (name) => containerClient.getBlockBlobClient(`${prefix}${safeName(name)}`);

  return {
    backend: 'azure-blob',

    /** Uploads a finished file, then deletes the local temp copy. */
    async putFile(name, sourcePath, { contentType } = {}) {
      await blobFor(name).uploadFile(sourcePath, { blobHTTPHeaders: { blobContentType: contentType || 'application/octet-stream' } });
      await fs.promises.rm(sourcePath, { force: true });
    },

    async openRead(name) {
      try {
        const res = await blobFor(name).download();
        return { stream: res.readableStreamBody, size: res.contentLength };
      } catch (err) {
        if (err.statusCode === 404) return null;
        throw err;
      }
    },

    async remove(name) {
      await blobFor(name).deleteIfExists();
    },
  };
}

export async function storageFromEnv(env, { filesDir }) {
  const backend = (env.STORAGE_BACKEND || 'local').toLowerCase();
  if (backend === 'local') return createLocalStorage(filesDir);
  if (backend === 'azure-blob') {
    return createBlobStorage({
      account: env.AZURE_STORAGE_ACCOUNT,
      container: env.AZURE_STORAGE_CONTAINER || 'documents',
      connectionString: env.AZURE_STORAGE_CONNECTION_STRING,
      prefix: env.AZURE_STORAGE_PREFIX || '',
      createContainer: env.AZURE_STORAGE_CREATE_CONTAINER === 'true', // emulator only; Terraform creates the real one
    });
  }
  throw new Error(`STORAGE_BACKEND must be "local" or "azure-blob", not "${backend}"`);
}
